final List<String> happy = [
  "Entammede Jimikki",
  "Jimmiki Kammal",
  "Kalippu",
  "Manikya Malaraya",
  "Pistah",
  "Lailakame",
  "Attention Please",
  "Appangalembadum",
  "Thalatherichavar",
  "Muthuchippi",
  "Malare",
  "Mandaarame",
  "Nokki Nokki",
  "Ethu Kari Raavilum",
  "Kilukkam",
  "Chinna Chinna",
  "Pranayame",
  "Ee Shishirakaalam",
  "Enthinu Veroru",
  "Thudakkam Mangalyam",
  "Mazhaye Thoomazhaye",
  "Kaikottum Kandittilla",
  "Doore Doore",
  "Thaniye Mizhikal",
  "Pavizha Mazha",
  "Vennilave",
  "Ee Kathiloru",
  "Gazab Ka Hai Din",
  "Aaromale",
  "Veruthe",
  "Manjadickel",
  "Aanakallan",
  "Pookkal Panineer",
  "Etho Mazhayil",
  "Nenjodu Cherthu",
  "Manikurumbe",
  "Ee Raathri",
  "Chundari Penne",
  "Enthavo",
  "Kaikkottum",
  "Jeevamshamayi",
  "Nee Himamazhayayi",
  "Pranayame",
  "Payye Veeshum",
  "Neelakasham",
  "Kanneer Thullikal",
  "Kannondu Chollanu",
  "Nilaave Maayumo",
  "Onnam Ragam",
  "Uyirin Nadhiye"
];

final List<String> neutral = [
  "Akale",
  "Ee Kaattu",
  "Mazhaye",
  "Karalinte",
  "Thamarapoovil",
  "Enthinu Veroru",
  "Aaradhike",
  "Thaazhvaram",
  "Mizhi Mizhi",
  "Kannil Kannil",
  "Nee En",
  "Vaanille",
  "Pranayavarnangal",
  "Karthaave",
  "Nenjodu Cherthu",
  "Mazhayil",
  "Pularippo",
  "Ayalathe",
  "Parudeesa",
  "Thiruvaavaniraavu",
  "Kaathirunnu",
  "Ente Mavum",
  "Theevandi",
  "Aaro Nenjil",
  "Sanchari",
  "Pachapoove",
  "Kaanil Mizhiyil",
  "Uyire",
  "Aaradhike",
  "Vathilil",
  "Puthiyoru",
  "Oro Pakal",
  "Earan Kaatin",
  "Theerame",
  "Neelakasham",
  "Parudeesa",
  "Ee Kaattu",
  "Mizhiyil Ninnum",
  "Thaazhvaram",
  "Kaathirunnu",
  "Mazhaye",
  "Vennila Chandanakinnam",
  "Pranayavarnangal",
  "Uyirin Nadhiye",
  "Ee Shishirakaalam",
  "Manikya Malaraya",
  "Pachapoove",
  "Karthaave",
  "Neelakasham",
  "Parudeesa"
];

final List<String> inspiring = [
  "Jeevamshamayi",
  "Nokki Nokki",
  "Ee Shishirakaalam",
  "Poomuthole",
  "Doore Doore",
  "Akale",
  "Aaradhike",
  "Kaikkottum",
  "Entammede Jimikki",
  "Pavizha Mazha",
  "Manikya Malaraya",
  "Pistah",
  "Lailakame",
  "Attention Please",
  "Appangalembadum",
  "Thalatherichavar",
  "Muthuchippi",
  "Malare",
  "Mandaarame",
  "Ethu Kari Raavilum",
  "Kilukkam",
  "Chinna Chinna",
  "Pranayame",
  "Enthinu Veroru",
  "Thudakkam Mangalyam",
  "Mazhaye Thoomazhaye",
  "Kaikottum",
  "Thaniye Mizhikal",
  "Vennilave",
  "Ee Kathiloru",
  "Gazab Ka Hai Din",
  "Aaromale",
  "Veruthe",
  "Manjadickel",
  "Aanakallan",
  "Pookkal Panineer",
  "Etho Mazhayil",
  "Nenjodu Cherthu",
  "Manikurumbe",
  "Ee Raathri",
  "Chundari Penne",
  "Enthavo",
  "Jeevamshamayi",
  "Nee Himamazhayayi",
  "Pranayame",
  "Payye Veeshum",
  "Neelakasham",
  "Kanneer Thullikal",
  "Kannondu Chollanu",
  "Nilaave Maayumo"
];

final List<String> melody = [
  "Nostalgia",
  "Kanninima Neele",
  "Aayiram Kannumai",
  "Kathirunnu Kathirunnu",
  "Pranayame",
  "Enthinu Veroru",
  "Mizhiyazhaku",
  "Thamarapoovil",
  "Ezhu Swarangalum",
  "Karukara",
  "Akale",
  "Ee Kaattu",
  "Mazhaye",
  "Karalinte",
  "Enthinu Veroru",
  "Aaradhike",
  "Thaazhvaram",
  "Mizhi Mizhi",
  "Kannil Kannil",
  "Nee En",
  "Vaanille",
  "Pranayavarnangal",
  "Karthaave",
  "Nenjodu Cherthu",
  "Mazhayil",
  "Pularippo",
  "Ayalathe",
  "Parudeesa",
  "Thiruvaavaniraavu",
  "Kaathirunnu",
  "Ente Mavum",
  "Theevandi",
  "Aaro Nenjil",
  "Sanchari",
  "Pachapoove",
  "Kaanil Mizhiyil",
  "Uyire",
  "Aaradhike",
  "Vathilil",
  "Puthiyoru",
  "Oro Pakal",
  "Earan Kaatin",
  "Theerame",
  "Neelakasham",
  "Parudeesa",
  "Ee Kaattu",
  "Mizhiyil Ninnum",
  "Thaazhvaram",
  "Kaathirunnu",
  "Mazhaye"
];

final List<String> motivating = [
  "Manikya Malaraya",
  "Jeevamshamayi",
  "Entammede Jimikki",
  "Kalippu",
  "Pistah",
  "Lailakame",
  "Attention Please",
  "Appangalembadum",
  "Thalatherichavar",
  "Muthuchippi",
  "Malare",
  "Mandaarame",
  "Nokki Nokki",
  "Ethu Kari Raavilum",
  "Kilukkam",
  "Chinna Chinna",
  "Pranayame",
  "Ee Shishirakaalam",
  "Enthinu Veroru",
  "Thudakkam Mangalyam",
  "Mazhaye Thoomazhaye",
  "Kaikottum",
  "Doore Doore",
  "Thaniye Mizhikal",
  "Pavizha Mazha",
  "Vennilave",
  "Ee Kathiloru",
  "Gazab Ka Hai Din",
  "Aaromale",
  "Veruthe",
  "Manjadickel",
  "Aanakallan",
  "Pookkal Panineer",
  "Etho Mazhayil",
  "Nenjodu Cherthu",
  "Manikurumbe",
  "Ee Raathri",
  "Chundari Penne",
  "Enthavo",
  "Kaikkottum",
  "Jeevamshamayi",
  "Nee Himamazhayayi",
  "Pranayame",
  "Payye Veeshum",
  "Neelakasham",
  "Kanneer Thullikal",
  "Kannondu Chollanu",
  "Nilaave Maayumo",
  "Onnam Ragam"
];
